#!/usr/bin/env bash
# Single-container config generator for the OSS quickstart Docker
# image. Writes /etc/boss-<name>-api.toml + /etc/boss-step-effects-
# runner.toml at container start so the API binaries (each of which
# defaults --config to /etc/boss-<name>.toml) have something to read.
#
# The ONE config generator since 2026-09-18: the bare-metal deploy's
# heredoc twin (infra/deploy-services.sh) had drifted from this one
# three ways and was deleted with that path (backlog e109bd71). The
# single-container assumption means every cross-service URL collapses
# to 127.0.0.1:<port>, and there's no scratch DB (only prod).
#
# Reads the canonical port table from `boss-ports-list` so a port
# rename in boss-ports lands here for free.
#
# Env inputs (all optional; sensible defaults):
#   DATABASE_URL          postgres URL (default: postgres://boss:boss@postgres:5432/boss)
#   BOSS_NATS_URL         nats URL (default: nats://nats:4222)
#   ETC_DIR               where to write configs (default: /etc)
#   BOSS_FILES_ROOT       durable directory for file_refs bytes; unset
#                         means the file store stays off (see content)
#
# Idempotent — re-running overwrites cleanly.

set -eu

DB_URL="${DATABASE_URL:-postgres://boss:boss@postgres:5432/boss}"
NATS_URL="${BOSS_NATS_URL:-nats://nats:4222}"
ETC_DIR="${ETC_DIR:-/etc}"

if ! command -v boss-ports-list >/dev/null 2>&1; then
    echo "FATAL: boss-ports-list not on PATH — image is malformed" >&2
    exit 1
fi

# Build name → port lookup tables. Paired services have a prod port
# + a scratch port; the docker stack runs only prod, so we ignore
# the scratch column.
declare -A PORT
while IFS=: read -r name prod scratch; do
    [[ -z "$name" ]] && continue
    PORT["$name"]="$prod"
done < <(boss-ports-list --paired)
while IFS=: read -r name prod; do
    [[ -z "$name" ]] && continue
    PORT["$name"]="$prod"
done < <(boss-ports-list --solo)

write_config() {
    local name="$1"
    local path="$ETC_DIR/boss-${name}-api.toml"
    shift
    local body
    body="$(cat)"
    printf '%s\n' "$body" > "$path"
    echo "  wrote $path"
}

p() { echo "${PORT[$1]:?unknown service: $1}"; }

echo "==> generate-configs: writing /etc/boss-*.toml"

# ------------ paired services (run as -api binary, prod-only here) ----------

write_config shipping <<EOF
# Generated by infra/oss-quickstart/generate-configs.sh
postgres_url = "$DB_URL"
http_bind = "0.0.0.0:$(p shipping)"
nats_url = "$NATS_URL"
classes_api_url = "http://127.0.0.1:$(p classes)"
EOF

write_config messages <<EOF
# Generated by infra/oss-quickstart/generate-configs.sh
postgres_url = "$DB_URL"
http_bind = "0.0.0.0:$(p messages)"
nats_url = "$NATS_URL"
events_retention_days = 90
classes_api_url = "http://127.0.0.1:$(p classes)"
EOF

write_config inventory <<EOF
# Generated by infra/oss-quickstart/generate-configs.sh
postgres_url = "$DB_URL"
http_bind = "0.0.0.0:$(p inventory)"
nats_url = "$NATS_URL"
shipping_api_url = "http://127.0.0.1:$(p shipping)"
classes_api_url = "http://127.0.0.1:$(p classes)"
EOF

write_config commerce <<EOF
# Generated by infra/oss-quickstart/generate-configs.sh
postgres_url = "$DB_URL"
http_bind = "0.0.0.0:$(p commerce)"
nats_url = "$NATS_URL"
people_api_url = "http://127.0.0.1:$(p people)"
classes_api_url = "http://127.0.0.1:$(p classes)"
EOF

# calendar_api_url switches on the PTO endpoint: unset, POST
# /api/people/pto answered 503 on every container pod (backlog
# 6777fecf, found by the url-equality pin in generate_configs_sh.rs).
# subject_kinds_api_url is deliberately NOT written: PeopleApiConfig
# declares it but no people handler consults the client — that pin's
# URLS_NOT_WRITTEN carries the reason.
write_config people <<EOF
# Generated by infra/oss-quickstart/generate-configs.sh
postgres_url = "$DB_URL"
http_bind = "0.0.0.0:$(p people)"
nats_url = "$NATS_URL"
assets_api_url = "http://127.0.0.1:$(p assets)"
classes_api_url = "http://127.0.0.1:$(p classes)"
locations_api_url = "http://127.0.0.1:$(p locations)"
calendar_api_url = "http://127.0.0.1:$(p calendar)"
EOF

# Accounts service (split out of people-api 2026-06): NATS publisher for
# account-team/notes/risk events, Postgres projection state, classes
# lookups for team-role validation, assets for open-ticket counts.
write_config accounts <<EOF
# Generated by infra/oss-quickstart/generate-configs.sh
postgres_url = "$DB_URL"
http_bind = "0.0.0.0:$(p accounts)"
nats_url = "$NATS_URL"
classes_api_url = "http://127.0.0.1:$(p classes)"
assets_api_url = "http://127.0.0.1:$(p assets)"
EOF

write_config assets <<EOF
# Generated by infra/oss-quickstart/generate-configs.sh
postgres_url = "$DB_URL"
http_bind = "0.0.0.0:$(p assets)"
nats_url = "$NATS_URL"
people_api_url = "http://127.0.0.1:$(p people)"
catalog_api_url = "http://127.0.0.1:$(p catalog)"
inventory_api_url = "http://127.0.0.1:$(p inventory)"
classes_api_url = "http://127.0.0.1:$(p classes)"
EOF

write_config catalog <<EOF
# Generated by infra/oss-quickstart/generate-configs.sh
postgres_url = "$DB_URL"
http_bind = "0.0.0.0:$(p catalog)"
nats_url = "$NATS_URL"
assets_api_url = "http://127.0.0.1:$(p assets)"
classes_api_url = "http://127.0.0.1:$(p classes)"
EOF

write_config calendar <<EOF
# Generated by infra/oss-quickstart/generate-configs.sh
postgres_url = "$DB_URL"
http_bind = "0.0.0.0:$(p calendar)"
nats_url = "$NATS_URL"
EOF

# calendar_api_url switches on the step reservation hook: boss-jobs-api
# builds its calendar client only when this is set, and until 2026-09-24
# nothing wrote it, so no step on any instance could reserve (backlog
# aa6b4b5c, design e1dba350). boss-calendar-api runs in this container
# on every tenant — the launcher gates it on no module.
#
# subject_kinds_api_url switches on subject-kind validation: unset, the
# jobs API admitted a packet on any subject-kind string (backlog
# b224ab3c). boss-subject-kinds-api is likewise gated on no module.
# The *_api_url keys below are held equal to JobsApiConfig's fields by
# boss-testing's generate_configs_sh.rs (backlog 839ba062), as every
# block's are to its own service's config struct (backlog 6777fecf).
write_config jobs <<EOF
# Generated by infra/oss-quickstart/generate-configs.sh
postgres_url = "$DB_URL"
http_bind = "0.0.0.0:$(p jobs)"
nats_url = "$NATS_URL"
classes_api_url = "http://127.0.0.1:$(p classes)"
calendar_api_url = "http://127.0.0.1:$(p calendar)"
subject_kinds_api_url = "http://127.0.0.1:$(p subject-kinds)"
EOF

# ------------ solo services -------------------------------------------------

write_config ml <<EOF
# Generated by infra/oss-quickstart/generate-configs.sh
postgres_url = "$DB_URL"
http_bind = "0.0.0.0:$(p ml)"
EOF

write_config ledger <<EOF
# Generated by infra/oss-quickstart/generate-configs.sh
postgres_url = "$DB_URL"
http_bind = "0.0.0.0:$(p ledger)"
nats_url = "$NATS_URL"
classes_api_url = "http://127.0.0.1:$(p classes)"
EOF

# file_refs — the content-addressed per-packet blob store (backlog
# 6280be03, 2026-09-23). Built and never switched on: this block wrote
# no [files] table, so boss-content-api answered 503 "unconfigured" on
# every /api/files path. It is written ONLY when the deployment names
# BOSS_FILES_ROOT, because the root must be DURABLE and backed up — a
# default path would keep every attachment on the container's writable
# layer, and the next container would restore pointers to nothing. The
# cluster names it on a declared PVC (infra/cluster/manifests/boss.yaml,
# which boss-backup.yaml archives beside the dump); the quickstart on a
# named volume (docker-compose.yml). policy_api_url is what makes the
# store policy-checked: without it the service falls back to a
# permissive client and any caller may attach to anything. Policy runs
# in the same container, on the port boss-ports gives it.
{
    cat <<EOF
# Generated by infra/oss-quickstart/generate-configs.sh
postgres_url = "$DB_URL"
http_bind = "0.0.0.0:$(p content)"
nats_url = "$NATS_URL"
policy_api_url = "http://127.0.0.1:$(p policy)"
EOF
    if [[ -n "${BOSS_FILES_ROOT:-}" ]]; then
        cat <<EOF

[files]
root = "$BOSS_FILES_ROOT"
EOF
    fi
} | write_config content

write_config policy <<EOF
# Generated by infra/oss-quickstart/generate-configs.sh
# (boss-policy-api takes its port from BOSS_POLICY_PORT env if set.)
port = $(p policy)
EOF

write_config classes <<EOF
# Generated by infra/oss-quickstart/generate-configs.sh
postgres_url = "$DB_URL"
http_bind = "0.0.0.0:$(p classes)"
EOF

write_config locations <<EOF
# Generated by infra/oss-quickstart/generate-configs.sh
postgres_url = "$DB_URL"
http_bind = "0.0.0.0:$(p locations)"
EOF

write_config subject-kinds <<EOF
# Generated by infra/oss-quickstart/generate-configs.sh
postgres_url = "$DB_URL"
http_bind = "0.0.0.0:$(p subject-kinds)"
EOF

# Audit-log read surface (split out of people-api 2026-06): reads
# audit_log, emits no new events — Postgres URL + bind, no NATS.
write_config events <<EOF
# Generated by infra/oss-quickstart/generate-configs.sh
postgres_url = "$DB_URL"
http_bind = "0.0.0.0:$(p events)"
EOF

write_config products <<EOF
# Generated by infra/oss-quickstart/generate-configs.sh
postgres_url = "$DB_URL"
http_bind = "0.0.0.0:$(p products)"
nats_url = "$NATS_URL"
classes_api_url = "http://127.0.0.1:$(p classes)"
EOF

# No nats_url: campaigns emits via the transactional outbox (#118);
# boss-event-relay moves staged events to audit_log + NATS.
write_config campaigns <<EOF
# Generated by infra/oss-quickstart/generate-configs.sh
postgres_url = "$DB_URL"
http_bind = "0.0.0.0:$(p campaigns)"
EOF

# Same outbox-only shape as campaigns.
write_config customers <<EOF
# Generated by infra/oss-quickstart/generate-configs.sh
postgres_url = "$DB_URL"
http_bind = "0.0.0.0:$(p customers)"
EOF

# ------------ dispatcher (not an -api binary) -------------------------------

cat > "$ETC_DIR/boss-dispatcher.toml" <<EOF
# Generated by infra/oss-quickstart/generate-configs.sh
postgres_url = "$DB_URL"
nats_url = "$NATS_URL"
rules_path = "/opt/boss/infra/dispatcher/rules"
EOF
echo "  wrote $ETC_DIR/boss-dispatcher.toml"

echo "==> generate-configs: done"
