//! Emits `EXPECTED_MIGRATIONS` — the migrations THIS build's tree holds,
//! in migration order — for `src/schema_level.rs`, which judges the live
//! `schema_migrations` ledger against it on every `/api/jobs/health`
//! (design a5323701, backlog 7c298c34).
//!
//! The order is not restated here: `schema_order.rs` in boss-testing is
//! its one definition (it already serves `migrate.sh`'s mirror in
//! boss-testing's own build script and the equality test there), and
//! this script `include!`s the same file, so the list the jobs API
//! judges by cannot drift from the list TestDb loads (CLAUDE.md §9a).
//!
//! Names only, with their `.sql` suffix, because that is what
//! `migrate.sh` writes into `schema_migrations.id`. No SQL is embedded:
//! the service needs to know WHICH migrations its tree holds, not what
//! they say.

use std::path::PathBuf;

// The file also carries the fingerprint helpers boss-testing needs;
// only the sort key is used here.
#[expect(
    dead_code,
    reason = "schema_order.rs also carries the fingerprint helpers boss-testing's TestDb reads; they are included whole, so the order stays one file"
)]
mod order {
    include!("../boss-testing/schema_order.rs");

    /// The one sort key, reachable from outside this module.
    pub(super) fn sort_key(name: &str) -> (u64, String) {
        schema_sort_key(name)
    }
}

fn main() {
    let crate_dir = PathBuf::from(
        std::env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by cargo"),
    );
    // crates/core/boss-jobs -> repo root
    let schema_dir = crate_dir
        .join("../../../infra/postgres/schema")
        .canonicalize()
        .expect("infra/postgres/schema must exist relative to the crate root");
    // A directory path makes cargo rescan it: a migration added,
    // removed or renamed reruns this script.
    println!("cargo:rerun-if-changed={}", schema_dir.display());
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=../boss-testing/schema_order.rs");

    let mut names: Vec<String> = std::fs::read_dir(&schema_dir)
        .unwrap_or_else(|e| panic!("reading {}: {e}", schema_dir.display()))
        .filter_map(|e| e.ok())
        .filter(|e| e.path().is_file())
        .map(|e| e.file_name().to_string_lossy().into_owned())
        .filter(|n| n.ends_with(".sql"))
        .collect();
    names.sort_by_key(|n| order::sort_key(n));

    // An empty list would make every ledger read "migrated" — pending 0
    // against nothing. Refuse at build time instead.
    assert!(
        !names.is_empty(),
        "{} holds no .sql migrations",
        schema_dir.display()
    );

    let mut out = String::from(
        "// @generated by build.rs from infra/postgres/schema/*.sql — do not edit.\n\
         pub(crate) const EXPECTED_MIGRATIONS: &[&str] = &[\n",
    );
    for name in &names {
        out.push_str(&format!("    {name:?},\n"));
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR is set by cargo"))
        .join("expected_migrations.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("writing {}: {e}", dest.display()));
}
