//! Two jobs. (1) Stamp the binary with the commit it was built from, so
//! the operator's own tool can say when it is stale (895c9a3b). (2)
//! Generate the ops allowlist table `boss ops` compiles in, from the
//! directory `infra/ops/verbs/` — see `verb_files` below.
//!
//! On the dev pod `boss` is whatever `cargo build -p boss-cli` last
//! produced, and NOTHING refreshes it: measured 2026-09-10, the binary
//! running every gate launch was eleven hours and two trains behind
//! main, so a guard that had landed (`--park-*` refusing without an
//! item) was unenforced on the one box that gates, silently — a removed
//! flag fails loudly, changed behaviour behind the same flag just does
//! the old thing. The floor is that the binary SAYS what it is: this
//! script reads `git rev-parse HEAD` at build time and, where there is
//! no git (an image build passes the sha as `BOSS_BUILD_COMMIT`, the
//! same variable every service already reports on /health), falls back
//! to that, and to `unknown` — never to a guess.

use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    verb_files();
    let from_git = Command::new("git")
        .args(["rev-parse", "HEAD"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .filter(|s| !s.is_empty());
    let sha = from_git
        .or_else(|| std::env::var("BOSS_BUILD_COMMIT").ok())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| "unknown".to_string());
    println!("cargo:rustc-env=BOSS_CLI_BUILT_FROM={sha}");
    println!("cargo:rerun-if-env-changed=BOSS_BUILD_COMMIT");
    // RERUN EVERY BUILD. This script used to name the checkout's HEAD
    // file as its one rerun key, and that was wrong twice over. On a
    // branch, HEAD is `ref: refs/heads/x` and a commit moves the ref
    // file, not HEAD, so the stamp lagged every commit. And worktrees
    // sharing one target dir share this script's unit: the key the LAST
    // worktree wrote (`/work/boss/.git/worktrees/gaterebase/HEAD`) is
    // what cargo checks when the NEXT worktree builds, so on 2026-09-12
    // the pod's `boss --version` answered 47a31701 for a binary just
    // built from a7c3bf4f — the freshness door (895c9a3b) saying
    // "current" about a stale stamp, which is the one thing it exists
    // not to do. A path that never exists makes cargo run this script
    // on every build; it costs one `git rev-parse` (milliseconds), and
    // boss-cli itself recompiles only when the sha it is handed changes.
    println!("cargo:rerun-if-changed=.boss-built-from-is-recomputed-every-build");
}

/// `VERB_FILES: &[(&str, &str)]` — every `infra/ops/verbs/*.json`, as
/// (verb name, `include_str!` of the file), written to OUT_DIR for
/// `src/ops_request.rs` to `include!`.
///
/// THE DIRECTORY IS THE ALLOWLIST (backlog 5086842d). `boss ops`
/// applies the runner's rules at the terminal, so it compiles the
/// allowlist in; `include_str!` needs literal paths at compile time, so
/// — exactly as boss-testing's build.rs derives `SCHEMA_FILES` from
/// `infra/postgres/schema/` — this script lists the directory at build
/// time and emits the literals. The verb's name is its file name, the
/// same rule `infra/ops/verbs-allowlist.sh` applies for the runner and
/// the lints; a test in ops_request.rs pins the compiled set to the
/// directory as it stands at test time, which is also what catches a
/// `VERB_FILES` linked from a neighbouring checkout's build (the shared
/// target-dir staleness boss-testing's build.rs documents).
///
/// A README beside the verbs is prose, not a verb: only `*.json` is
/// read. An empty directory is a build-time panic, not an empty
/// allowlist that refuses every `boss ops` as "unknown verb".
fn verb_files() {
    let crate_dir = PathBuf::from(
        std::env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by cargo"),
    );
    // crates/orchestrators/boss-cli -> repo root
    let verbs_dir = crate_dir
        .join("../../../infra/ops/verbs")
        .canonicalize()
        .expect("infra/ops/verbs must exist relative to the crate root");
    // The DIRECTORY notices an add or remove; the per-file lines below
    // make each file's content part of the dependency too.
    println!("cargo:rerun-if-changed={}", verbs_dir.display());

    let mut names: Vec<String> = std::fs::read_dir(&verbs_dir)
        .unwrap_or_else(|e| panic!("reading {}: {e}", verbs_dir.display()))
        .filter_map(|e| e.ok())
        .filter(|e| e.path().is_file())
        .map(|e| e.file_name().to_string_lossy().into_owned())
        .filter_map(|n| n.strip_suffix(".json").map(str::to_string))
        .collect();
    names.sort();
    assert!(
        !names.is_empty(),
        "{} holds no verb (*.json) — an empty allowlist is a fault, not a policy",
        verbs_dir.display()
    );

    let mut out = String::from(
        "// @generated by build.rs from infra/ops/verbs/*.json — do not edit.\n\
         const VERB_FILES: &[(&str, &str)] = &[\n",
    );
    for name in &names {
        let path = verbs_dir.join(format!("{name}.json"));
        println!("cargo:rerun-if-changed={}", path.display());
        out.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            name,
            path.display().to_string()
        ));
    }
    out.push_str("];\n");

    let dest = Path::new(&std::env::var_os("OUT_DIR").expect("OUT_DIR is set by cargo"))
        .join("verb_files.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("writing {}: {e}", dest.display()));
}
