//! The database's migration level, READ — so "migrated" is a reading on
//! `/api/jobs/health`, not an assumption (design a5323701, backlog
//! 7c298c34).
//!
//! WHY. `capabilities.commit` says which build is RUNNING. It never said
//! whether that build's migrations had RUN, so a reader comparing it to
//! a sha got YES the moment the binary rolled — the false-green shape,
//! and the incident `boss-cli/src/running.rs` carries in its header. In
//! the cluster the `boss-init` container migrates before the pod
//! serves, so on our instance the two usually agree; but that is an
//! argument, not a record, and it does not hold for a database
//! repointed or restored after the pod started, an instance migrated
//! `--without` a module, or any instance whose schema we do not
//! converge (the OSS quickstart, a hosted customer's).
//!
//! WHAT IS REPORTED. `head` — the highest applied migration by name —
//! and `pending` / `first_pending` — the migrations in the running
//! build's OWN tree that the ledger does not hold. `pending` is a
//! verdict any reader can use without a checkout; a bare count of
//! applied rows was rejected because it compares to nothing.
//!
//! WHEN. On every health request, never cached at startup: a startup
//! read is a belief about the past, and a repointed database is exactly
//! the case it would miss. One read of a ~180-row table, bounded by
//! [`READ_TIMEOUT`] so a slow database makes the answer `null`, never a
//! hung health check.
//!
//! Hexagonal: the pure [`judge`], a port ([`SchemaLedger`]), and the
//! Postgres adapter behind the `postgres` feature.

use std::collections::HashSet;
use std::sync::Arc;
use std::time::Duration;

use async_trait::async_trait;
use boss_core::startup::Schema;

// The migration ORDER has one definition, boss-testing's
// `schema_order.rs`, which this crate's build script and this module
// both `include!` — so `head` is chosen by the same rule `migrate.sh`
// applies and TestDb loads by. Only the sort key is used here.
#[expect(
    dead_code,
    reason = "schema_order.rs also carries the fingerprint helpers boss-testing's TestDb reads; they are included whole, so the order stays one file"
)]
mod order {
    include!("../../boss-testing/schema_order.rs");

    /// The one sort key, reachable from outside this module.
    pub(super) fn sort_key(name: &str) -> (u64, String) {
        schema_sort_key(name)
    }
}

// `EXPECTED_MIGRATIONS`: this build's tree, in order, generated by
// build.rs from `infra/postgres/schema/*.sql`.
include!(concat!(env!("OUT_DIR"), "/expected_migrations.rs"));

/// The migrations the running build's own tree holds, in migration
/// order, as `schema_migrations.id` spells them (`03-jobs.sql`).
pub fn expected_migrations() -> &'static [&'static str] {
    EXPECTED_MIGRATIONS
}

/// How long a health request waits for the ledger before answering
/// `null`. The cluster watchdog reads health with an 8 s budget; this
/// leaves it most of that.
pub const READ_TIMEOUT: Duration = Duration::from_secs(2);

/// PURE: judge the ledger's applied ids against the build's expected
/// list.
///
/// `head` is chosen over EVERY applied id, not only the ones this build
/// knows: a database AHEAD of the build (a rollback onto an older
/// image) must say so, and its head is then a name this tree does not
/// hold. `pending` counts the expected ids the ledger lacks, and
/// `first_pending` is the first of them in `expected`'s order.
pub fn judge(applied: &[String], expected: &[&str]) -> Schema {
    let head = applied.iter().max_by_key(|id| order::sort_key(id)).cloned();
    let held: HashSet<&str> = applied.iter().map(String::as_str).collect();
    let missing: Vec<&str> = expected
        .iter()
        .copied()
        .filter(|id| !held.contains(id))
        .collect();
    Schema {
        head,
        pending: u32::try_from(missing.len()).unwrap_or(u32::MAX),
        first_pending: missing.first().map(|id| id.to_string()),
    }
}

/// The port: what `schema_migrations` holds.
#[async_trait]
pub trait SchemaLedger: Send + Sync {
    /// Every applied migration id, in no particular order. `Err` when
    /// the ledger cannot be read — including when it does not exist.
    async fn applied(&self) -> Result<Vec<String>, String>;
}

/// The reading `/api/jobs/health` serves: the ledger judged against
/// this build, or `None` — "could not read" — when the read fails or
/// outlasts [`READ_TIMEOUT`]. Never a zero.
pub async fn read(ledger: &Arc<dyn SchemaLedger>) -> Option<Schema> {
    read_within(ledger, READ_TIMEOUT).await
}

/// [`read`] with the bound as an argument, so a test can prove the
/// bound without waiting it out.
pub async fn read_within(ledger: &Arc<dyn SchemaLedger>, bound: Duration) -> Option<Schema> {
    match tokio::time::timeout(bound, ledger.applied()).await {
        Ok(Ok(applied)) => Some(judge(&applied, expected_migrations())),
        Ok(Err(e)) => {
            tracing::warn!(error = %e, "schema_migrations could not be read; health reports schema: null");
            None
        }
        Err(_) => {
            tracing::warn!(
                timeout_ms = bound.as_millis() as u64,
                "schema_migrations read timed out; health reports schema: null"
            );
            None
        }
    }
}

/// Postgres adapter: one read of `schema_migrations`, the ledger
/// `infra/postgres/migrate.sh` writes.
#[cfg(feature = "postgres")]
pub struct PgSchemaLedger {
    pool: sqlx::PgPool,
}

#[cfg(feature = "postgres")]
impl PgSchemaLedger {
    pub fn new(pool: sqlx::PgPool) -> Self {
        Self { pool }
    }
}

#[cfg(feature = "postgres")]
#[async_trait]
impl SchemaLedger for PgSchemaLedger {
    async fn applied(&self) -> Result<Vec<String>, String> {
        sqlx::query_scalar::<_, String>("SELECT id FROM schema_migrations")
            .fetch_all(&self.pool)
            .await
            .map_err(|e| e.to_string())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const TREE: &[&str] = &[
        "00-extensions.sql",
        "03-jobs.sql",
        "100-late-legacy.sql",
        "202609240000-twelve.sql",
        "20260924000000-fourteen.sql",
    ];

    fn applied(ids: &[&str]) -> Vec<String> {
        ids.iter().map(|s| s.to_string()).collect()
    }

    #[test]
    fn a_ledger_holding_the_whole_tree_is_migrated() {
        // Deliberately out of order: the ledger is a set.
        let s = judge(
            &applied(&[
                "20260924000000-fourteen.sql",
                "00-extensions.sql",
                "202609240000-twelve.sql",
                "100-late-legacy.sql",
                "03-jobs.sql",
            ]),
            TREE,
        );
        assert_eq!(
            s,
            Schema {
                head: Some("20260924000000-fourteen.sql".into()),
                pending: 0,
                first_pending: None,
            }
        );
    }

    #[test]
    fn a_build_ahead_of_its_schema_names_the_first_missing_migration() {
        let s = judge(
            &applied(&[
                "00-extensions.sql",
                "03-jobs.sql",
                "100-late-legacy.sql",
                "202609240000-twelve.sql",
            ]),
            TREE,
        );
        assert_eq!(s.head.as_deref(), Some("202609240000-twelve.sql"));
        assert_eq!(s.pending, 1);
        assert_eq!(
            s.first_pending.as_deref(),
            Some("20260924000000-fourteen.sql")
        );
    }

    #[test]
    fn a_missing_legacy_file_is_pending_even_below_the_head() {
        // `--without <module>` skips an entry and records nothing: the
        // head is current, and the skipped file is still honestly
        // pending — true, not a false alarm.
        let s = judge(
            &applied(&[
                "00-extensions.sql",
                "100-late-legacy.sql",
                "202609240000-twelve.sql",
                "20260924000000-fourteen.sql",
            ]),
            TREE,
        );
        assert_eq!(s.head.as_deref(), Some("20260924000000-fourteen.sql"));
        assert_eq!(s.pending, 1);
        assert_eq!(s.first_pending.as_deref(), Some("03-jobs.sql"));
    }

    #[test]
    fn an_empty_ledger_has_no_head_and_everything_pending() {
        let s = judge(&[], TREE);
        assert_eq!(
            s,
            Schema {
                head: None,
                pending: TREE.len() as u32,
                first_pending: Some("00-extensions.sql".into()),
            }
        );
    }

    #[test]
    fn the_head_is_chosen_numerically_not_lexically() {
        // `100-` sorts after `03-` numerically and before it lexically.
        let s = judge(&applied(&["03-jobs.sql", "100-late-legacy.sql"]), TREE);
        assert_eq!(s.head.as_deref(), Some("100-late-legacy.sql"));
    }

    #[test]
    fn a_database_ahead_of_the_build_names_a_head_this_tree_does_not_hold() {
        let mut ids = applied(TREE);
        ids.push("20991231000000-from-a-newer-build.sql".into());
        let s = judge(&ids, TREE);
        assert_eq!(
            s.head.as_deref(),
            Some("20991231000000-from-a-newer-build.sql")
        );
        assert_eq!(s.pending, 0);
    }

    #[test]
    fn the_expected_list_is_this_trees_schema_directory_in_order() {
        // The build script's output against the directory as it stands:
        // a stale build (a shared target dir that skipped the script)
        // would judge the ledger against someone else's tree.
        let dir = boss_testing::repo_root().join("infra/postgres/schema");
        let mut on_disk: Vec<String> = std::fs::read_dir(&dir)
            .unwrap()
            .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
            .filter(|n| n.ends_with(".sql"))
            .collect();
        on_disk.sort_by_key(|n| order::sort_key(n));
        assert_eq!(expected_migrations(), on_disk.as_slice());
    }

    struct Failing;
    #[async_trait]
    impl SchemaLedger for Failing {
        async fn applied(&self) -> Result<Vec<String>, String> {
            Err("relation \"schema_migrations\" does not exist".into())
        }
    }

    struct Slow;
    #[async_trait]
    impl SchemaLedger for Slow {
        async fn applied(&self) -> Result<Vec<String>, String> {
            tokio::time::sleep(READ_TIMEOUT * 10).await;
            Ok(Vec::new())
        }
    }

    #[tokio::test]
    async fn a_ledger_that_cannot_be_read_is_none_never_zero() {
        let ledger: Arc<dyn SchemaLedger> = Arc::new(Failing);
        assert_eq!(read(&ledger).await, None);
    }

    #[tokio::test]
    async fn a_ledger_slower_than_the_bound_is_none_not_a_hung_health_check() {
        let ledger: Arc<dyn SchemaLedger> = Arc::new(Slow);
        assert_eq!(read_within(&ledger, Duration::from_millis(20)).await, None);
    }
}
