#!/usr/bin/env bash
# Build + install the Boss browser bundles into the deploy generation.
#
# Two SPAs ship from this repo and BOTH land here: `apps/web` (the
# dashboard the gateway serves) and `apps/simulator` (the Simulator UX
# cockpit boss-simulator serves under /simulator). Plus the
# step-plugin JS bundles.
#
# It all lives IN the generation (deployment-as-network Q2): this
# builds and rsyncs into /usr/local/boss/releases/<sha>/{web-dist,
# simulator-dist,step-plugins}/, where <sha> is this checkout's HEAD —
# the generation deploy-services.sh stages for the same commit. Each
# service reads through the `current` symlink:
#   BOSS_STATIC_DIR=…/current/web-dist        (gateway; unit in
#                                              infra/gateway/)
#   BOSS_SIM_STATIC_DIR=…/current/simulator-dist
#                                             (boss-simulator; unit
#                                              generated by
#                                              deploy-services.sh
#                                              emit_unit — the only
#                                              definition, see §9a)
# so one symlink flip rolls every browser-facing surface back together
# with the binaries.
#
#   sudo ./infra/deploy-web.sh
#
# Destination resolution, in order:
#   1. an explicit BOSS_STATIC_DIR / BOSS_STEP_PLUGIN_DIR /
#      BOSS_SIM_STATIC_DIR override
#   2. releases/<HEAD sha>/ when that generation exists (the normal
#      services-then-web train order lands here, already live)
#   3. the `current` generation, when HEAD was never service-deployed
#      (a web-only iteration loop) — said out loud, since it updates
#      the live generation in place
#   4. the pre-generation paths (/var/lib/boss-web/dist), for a box
#      with no generation store yet
#
# Idempotent — safe to re-run. No service restart required: the
# browser picks up the new chunk filenames (from index.html) on next
# load. A hard-refresh may still be needed if the index.html itself
# is in the browser cache.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WEB_DIR="${REPO_ROOT}/apps/web"
DIST_SRC="${WEB_DIR}/dist"
SIM_WEB_DIR="${REPO_ROOT}/apps/simulator"
SIM_DIST_SRC="${SIM_WEB_DIR}/dist"

# Generation store paths, shared with deploy-services.sh +
# deploy-confirm.sh so they cannot drift.
# shellcheck source=infra/generation.sh
. "${REPO_ROOT}/infra/generation.sh"

GEN_DEST=""
if [[ -z "${BOSS_STATIC_DIR:-}" && -z "${BOSS_STEP_PLUGIN_DIR:-}" \
      && -z "${BOSS_SIM_STATIC_DIR:-}" ]]; then
    HEAD_KEY="$(gen_head_key "$REPO_ROOT")"
    CURRENT_KEY="$(gen_link_key current)"
    if [[ -n "$HEAD_KEY" && -d "$GEN_RELEASES/$HEAD_KEY" ]]; then
        GEN_DEST="$GEN_RELEASES/$HEAD_KEY"
        if [[ "$HEAD_KEY" == "$CURRENT_KEY" ]]; then
            echo "==> target: generation $HEAD_KEY (live)"
        else
            echo "==> target: generation $HEAD_KEY (staged, not current — goes live at its flip)"
        fi
    elif [[ -n "$CURRENT_KEY" && -d "$GEN_RELEASES/$CURRENT_KEY" ]]; then
        GEN_DEST="$GEN_RELEASES/$CURRENT_KEY"
        echo "==> target: LIVE generation $CURRENT_KEY (HEAD ${HEAD_KEY:-unknown} has no"
        echo "    generation of its own — web-only deploy updates the live one in place;"
        echo "    the next deploy-services.sh run gives this UI a generation of its own)"
    fi
fi
if [[ -n "$GEN_DEST" ]]; then
    DIST_DST="$GEN_DEST/web-dist"
    PLUGIN_DST="$GEN_DEST/step-plugins"
    SIM_DIST_DST="$GEN_DEST/simulator-dist"
else
    # Pre-generation box (or explicit override): the legacy fixed paths.
    DIST_DST="${BOSS_STATIC_DIR:-/var/lib/boss-web/dist}"
    PLUGIN_DST="${BOSS_STEP_PLUGIN_DIR:-/var/lib/boss/step-plugins}"
    SIM_DIST_DST="${BOSS_SIM_STATIC_DIR:-/var/lib/boss-simulator/dist}"
fi

if [[ ! -d "${WEB_DIR}" ]]; then
    echo "web source not found: ${WEB_DIR}" >&2
    exit 1
fi
if [[ ! -d "${SIM_WEB_DIR}" ]]; then
    echo "simulator web source not found: ${SIM_WEB_DIR}" >&2
    exit 1
fi

# Build as the invoking user — bun needs write to node_modules + the
# source dist dir, and those are owned by the dev user, not root. If
# the script is run with sudo, de-escalate for the build. `sudo -u`
# doesn't source `.bashrc` (only login shells do, and bash -lc
# sources `.bash_profile`/`.profile`), so we add bun's default
# install path manually — covers the common case where bun ships to
# ~/.bun/bin and is put on PATH by the user's `.bashrc`.
# Find bun. `$HOME/.bun/bin` for the invoking user is the common case
# and was the only case this handled — which fails on any box where the
# toolchain was installed under a different account than the one running
# the deploy. That is this playground: bun lives in dauld's home, the
# deploy runs as david, and the build died with "bun: command not found"
# while every other part of the script worked. The web bundle then
# silently stayed at whatever version was last built by hand, which is
# how a CSS fix committed at 23:42 was still not in the browser at 04:05
# and got reported as a bug twice.
#
# So: look in the obvious places and SAY which ones were tried.
find_bun() {
    local candidates=()
    command -v bun >/dev/null 2>&1 && { command -v bun; return 0; }
    [[ -n "${BOSS_BUN:-}" ]] && candidates+=("${BOSS_BUN}")
    [[ -n "${SUDO_USER:-}" ]] && candidates+=("$(getent passwd "${SUDO_USER}" | cut -d: -f6)/.bun/bin/bun")
    candidates+=("${HOME}/.bun/bin/bun" "/usr/local/bin/bun")
    # Any user's bun install. Last resort, but a deploy that cannot find
    # the toolchain is worse than one that looks a little harder.
    local h
    while IFS=: read -r _ _ _ _ _ h _; do
        [[ -x "$h/.bun/bin/bun" ]] && candidates+=("$h/.bun/bin/bun")
    done < <(getent passwd)
    local c
    for c in "${candidates[@]}"; do
        [[ -x "$c" ]] && { echo "$c"; return 0; }
    done
    {
        echo "bun not found. Tried:"
        printf '  %s\n' "${candidates[@]}"
        echo "Set BOSS_BUN=/path/to/bun, or install bun for the user running this."
    } >&2
    return 1
}

BUN="$(find_bun)" || exit 1

# Build as a user who can write node_modules + dist, not as root.
#
# Overridable because the caller sometimes knows better than SUDO_USER
# does. bootstrap-vm.sh builds the Rust side as $DEV_USER (default
# `boss`) while a human runs the script under sudo as themselves — so
# the default here would bun-build as the human into a checkout the
# cargo build owns, and leave node_modules split between two users.
BUILD_AS="${BUILD_AS:-${SUDO_USER:-$(id -un)}}"

# One build path for both SPAs — they are the same shape (a bun
# workspace member with a `build` script emitting dist/index.html) and
# a second copy of the de-escalation dance is a second place for the
# bun-not-found class of bug to come back.
build_bundle() {
    local label="$1" src_dir="$2"
    echo "==> building ${label} bundle (bun: ${BUN})"
    if [[ "${BUILD_AS}" != "$(id -un)" ]]; then
        sudo -u "${BUILD_AS}" env "PATH=$(dirname "${BUN}"):${PATH}" \
            bash -c "cd '${src_dir}' && bun run build"
    else
        (cd "${src_dir}" && PATH="$(dirname "${BUN}"):${PATH}" bun run build)
    fi
    if [[ ! -f "${src_dir}/dist/index.html" ]]; then
        echo "build output missing: ${src_dir}/dist/index.html" >&2
        exit 1
    fi
}

# rsync --delete so chunks renamed by the bundler don't pile up in
# the static dir. Keeps the dir size-stable across deploys.
install_bundle() {
    local label="$1" src="$2" dst="$3"
    echo "==> installing ${label} to ${dst}"
    mkdir -p "${dst}"
    rsync -a --delete "${src}/" "${dst}/"
}

build_bundle web "${WEB_DIR}"
install_bundle web "${DIST_SRC}" "${DIST_DST}"

# The Simulator UX — a SECOND SPA, served by boss-simulator (not the
# gateway) under /simulator. It used to live outside the generation
# store and outside this script: a separate deploy-simulator-web.sh
# had to be run BY HAND against a fixed /var/lib path, which nothing
# in the train ever did — so the playground ran with no bundle at all
# and boss-simulator served its "bundle not installed" stub. That
# script is gone; building here is what makes the cockpit ride the
# same generation as the dashboard, so a revert rolls both.
build_bundle simulator "${SIM_WEB_DIR}"
install_bundle simulator "${SIM_DIST_SRC}" "${SIM_DIST_DST}"

# Step-plugin bundles. Authored as static JS in `infra/step-plugins/`
# (no build step — each plugin is hand-authored vanilla DOM). Gateway
# serves them at `/plugins/*` through the generation symlink (see
# `crates/core/boss-gateway/src/plugin_files.rs` + BOSS_PLUGINS_DIR in
# the gateway unit). Without this copy the gateway returns 404 for
# every plugin URL the step_plugins registry references — which
# renders broken step surfaces in the SPA's Job Detail view. In the
# generation with the SPA, so a revert rolls both together.
PLUGIN_SRC="${REPO_ROOT}/infra/step-plugins"
if [[ -d "${PLUGIN_SRC}" ]]; then
    echo "==> installing step-plugin bundles to ${PLUGIN_DST}"
    mkdir -p "${PLUGIN_DST}"
    # Only copy the JS bundles — the README in that dir is author
    # docs, not a runtime asset.
    rsync -a --delete --include='*.js' --exclude='*' \
        "${PLUGIN_SRC}/" "${PLUGIN_DST}/"
fi

echo
echo "==> deploy complete"
echo "--- ${DIST_DST}"
ls -la "${DIST_DST}/" | head -10
echo "--- ${SIM_DIST_DST}"
ls -la "${SIM_DIST_DST}/" | head -10
