//! Generates the `SCHEMA_FILES` list that `src/test_db.rs` includes.
//!
//! The ordered migration list IS `infra/postgres/schema/*.sql`, sorted
//! by the `NNN-` prefix. `migrate.sh` derives it at runtime; `TestDb`
//! cannot, because it compiles the SQL in via `include_str!` and
//! `include_str!` needs literal paths at compile time. So this script
//! derives the same order at *build* time and emits it as Rust.
//!
//! This is the second half of one collapse. The list was once
//! maintained by hand in two places under a sync comment; it drifted
//! (`42-views.sql`, `43-event-facts.sql` reached the manifest and never
//! reached the Rust side, so every DB-backed test ran against a schema
//! missing those tables), which bought it an equality test — and the
//! equality test meant every migration touched the tail line of two
//! files. Generating this list from `manifest.txt` fixed the second
//! file. It left the first: a single contended tail line that any two
//! cars carrying a migration still conflicted on, which cost four
//! re-rails on 2026-08-13 and stranded two cars on 2026-08-14.
//!
//! So the manifest is gone too, and the directory is the definition.
//! Nothing is appended to add a migration — a file is dropped in — and
//! two cars adding migrations no longer touch a shared line at all.
//! CLAUDE.md §9a: prefer collapsing. This finishes it.
//!
//! Numeric sort on the prefix, not lexical: `100-` sorts after `20-`.

use std::path::{Path, PathBuf};

include!("schema_order.rs");

fn main() {
    let crate_dir = PathBuf::from(
        std::env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by cargo"),
    );
    // crates/core/boss-testing -> repo root
    let schema_dir = crate_dir
        .join("../../../infra/postgres/schema")
        .canonicalize()
        .expect("infra/postgres/schema must exist relative to the crate root");
    // The DIRECTORY is what notices an add or a remove: a new file
    // changes the directory's mtime and nothing else about it is
    // visible yet. The per-FILE lines emitted below are what make the
    // dependency real rather than mtime-shaped — the set of
    // `rerun-if-changed` directives is itself part of what cargo hands
    // to the units that depend on this script, so adding a migration
    // changes this script's OUTPUT and not merely a timestamp it once
    // looked at.
    println!("cargo:rerun-if-changed={}", schema_dir.display());
    println!("cargo:rerun-if-changed=build.rs");

    let mut entries: Vec<String> = std::fs::read_dir(&schema_dir)
        .unwrap_or_else(|e| panic!("reading {}: {e}", schema_dir.display()))
        .filter_map(|e| e.ok())
        .filter(|e| e.path().is_file())
        .map(|e| e.file_name().to_string_lossy().into_owned())
        .filter(|n| n.ends_with(".sql"))
        .collect();
    // Same ordering rule as migrate.sh's `sort -t- -k1,1n`: the numeric
    // prefix decides, and a file without one sorts last rather than
    // silently landing in the middle of the run.
    // The order is defined once, in schema_order.rs, which the equality
    // test includes too — the two Rust readers disagreed on 2026-09-09
    // and redded a train.
    entries.sort_by_key(|n| schema_sort_key(n));

    // An empty list would load an empty schema into every TestDb and
    // surface as "relation does not exist" a long way from the cause —
    // the exact failure this collapse exists to prevent. Fail loudly at
    // build time instead.
    assert!(
        !entries.is_empty(),
        "{} holds no .sql migrations",
        schema_dir.display()
    );

    let mut out = String::from(
        "// @generated by build.rs from infra/postgres/schema/*.sql — do not edit.\n\
         const SCHEMA_FILES: &[(&str, &str)] = &[\n",
    );
    // Each file is READ as well as named: one `rerun-if-changed` per
    // file, and the bytes that go into the fingerprint below.
    let mut read: Vec<(String, String)> = Vec::with_capacity(entries.len());
    for entry in &entries {
        let path = schema_dir.join(entry);
        println!("cargo:rerun-if-changed={}", path.display());
        let sql = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("reading migration {}: {e}", path.display()));
        let name = entry.strip_suffix(".sql").unwrap_or(entry);
        out.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            name,
            path.display().to_string()
        ));
        read.push((name.to_string(), sql));
    }
    out.push_str("];\n");

    // The list's own fingerprint, derived from what was just read —
    // never authored, and no second list to drift from (CLAUDE.md §9a).
    //
    // Two jobs. It puts a number in the generated file that CHANGES
    // whenever the list does, so the compiled artifact differs by
    // CONTENT and not only by a timestamp something compared. And it
    // gives the harness a build-time reading to compare against:
    // `test_db.rs` recomputes the same fingerprint over the list rustc
    // actually linked and over the schema directory as it stands at run
    // time, and refuses rather than loading a schema that is not the
    // one on disk.
    //
    // Why that run-time refusal is not belt-and-braces. On 2026-09-10 a
    // build on the dev pod linked a `SCHEMA_FILES` generated from a
    // DIFFERENT checkout. `infra/dev-shared-target.sh` points every
    // worktree on a machine at one CARGO_TARGET_DIR by design; cargo's
    // unit hash for this crate is identical in each of them; so the
    // rlib and this script's OUT_DIR are one shared artifact belonging
    // to whichever checkout built last. Measured: a checkout holding a
    // new migration was reported `Finished` with nothing recompiled,
    // against a list of its neighbour's files. No `rerun-if-changed`
    // directive can see that — the build script is not run at all, the
    // unit is simply "fresh" — which is why the refusal downstream is
    // the measure that closes it.
    let fingerprint =
        schema_set_fingerprint(read.iter().map(|(name, sql)| (name.as_str(), sql.as_str())));
    out.push_str(&format!(
        "\n// Fingerprint of the list above as THIS script read it, for the\n\
         // run-time check in test_db.rs.\n\
         const SCHEMA_FILES_FINGERPRINT: u64 = {fingerprint:#018x};\n"
    ));

    let dest = Path::new(&std::env::var_os("OUT_DIR").expect("OUT_DIR is set by cargo"))
        .join("schema_files.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("writing {}: {e}", dest.display()));
}
