//! Generates the `SCHEMA_FILES` list that `src/test_db.rs` includes.
//!
//! The ordered migration list IS `infra/postgres/schema/*.sql`, sorted
//! by the `NNN-` prefix. `migrate.sh` derives it at runtime; `TestDb`
//! cannot, because it compiles the SQL in via `include_str!` and
//! `include_str!` needs literal paths at compile time. So this script
//! derives the same order at *build* time and emits it as Rust.
//!
//! This is the second half of one collapse. The list was once
//! maintained by hand in two places under a sync comment; it drifted
//! (`42-views.sql`, `43-event-facts.sql` reached the manifest and never
//! reached the Rust side, so every DB-backed test ran against a schema
//! missing those tables), which bought it an equality test — and the
//! equality test meant every migration touched the tail line of two
//! files. Generating this list from `manifest.txt` fixed the second
//! file. It left the first: a single contended tail line that any two
//! cars carrying a migration still conflicted on, which cost four
//! re-rails on 2026-08-13 and stranded two cars on 2026-08-14.
//!
//! So the manifest is gone too, and the directory is the definition.
//! Nothing is appended to add a migration — a file is dropped in — and
//! two cars adding migrations no longer touch a shared line at all.
//! CLAUDE.md §9a: prefer collapsing. This finishes it.
//!
//! Numeric sort on the prefix, not lexical: `100-` sorts after `20-`.

use std::path::{Path, PathBuf};

fn main() {
    let crate_dir = PathBuf::from(
        std::env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by cargo"),
    );
    // crates/core/boss-testing -> repo root
    let schema_dir = crate_dir
        .join("../../../infra/postgres/schema")
        .canonicalize()
        .expect("infra/postgres/schema must exist relative to the crate root");
    // Adding or removing a schema file changes the directory's mtime.
    // Content edits to an individual .sql file need no watch here — the
    // emitted `include_str!` makes rustc itself track each one.
    println!("cargo:rerun-if-changed={}", schema_dir.display());
    println!("cargo:rerun-if-changed=build.rs");

    let mut entries: Vec<String> = std::fs::read_dir(&schema_dir)
        .unwrap_or_else(|e| panic!("reading {}: {e}", schema_dir.display()))
        .filter_map(|e| e.ok())
        .filter(|e| e.path().is_file())
        .map(|e| e.file_name().to_string_lossy().into_owned())
        .filter(|n| n.ends_with(".sql"))
        .collect();
    // Same ordering rule as migrate.sh's `sort -t- -k1,1n`: the numeric
    // prefix decides, and a file without one sorts last rather than
    // silently landing in the middle of the run.
    entries.sort_by_key(|n| {
        // u64, not u32: a `YYYYMMDDHHMMSS-` prefix is ~2.0e13 and would
        // overflow a u32 into the no-prefix arm. That arm happens to
        // sort timestamps last and, being a string tiebreak on equal
        // widths, happens to keep them chronological — accidentally
        // right, for a reason no reader could rely on. Parsed as what
        // it is, the ordering is intent rather than luck.
        let num: u64 = n
            .split('-')
            .next()
            .and_then(|p| p.parse().ok())
            .unwrap_or(u64::MAX);
        (num, n.clone())
    });

    // An empty list would load an empty schema into every TestDb and
    // surface as "relation does not exist" a long way from the cause —
    // the exact failure this collapse exists to prevent. Fail loudly at
    // build time instead.
    assert!(
        !entries.is_empty(),
        "{} holds no .sql migrations",
        schema_dir.display()
    );

    let mut out = String::from(
        "// @generated by build.rs from infra/postgres/schema/*.sql — do not edit.\n\
         const SCHEMA_FILES: &[(&str, &str)] = &[\n",
    );
    for entry in &entries {
        let path = schema_dir.join(entry);
        assert!(
            path.is_file(),
            "{} is not a readable migration file",
            path.display()
        );
        let name = entry.strip_suffix(".sql").unwrap_or(entry);
        out.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            name,
            path.display().to_string()
        ));
    }
    out.push_str("];\n");

    let dest = Path::new(&std::env::var_os("OUT_DIR").expect("OUT_DIR is set by cargo"))
        .join("schema_files.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("writing {}: {e}", dest.display()));
}
