// Bundles the phase-0 Svelte app into apps/web/dist/.
//
// Mirrors apps/web/src/build.ts so the two stacks are
// apples-to-apples. Uses bun-plugin-svelte to compile .svelte
// sources. The gateway's static dir points at whichever `dist/`
// we choose at deploy time (BOSS_STATIC_DIR env var).

import { SveltePlugin } from 'bun-plugin-svelte';
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join as pathJoin } from 'node:path';
import { spawnSync } from 'node:child_process';

const OUT = 'dist';
await rm(OUT, { recursive: true, force: true });

// ---------------------------------------------------------------------------
// Codegen: derive `src/_generated/ports.ts` from `boss-ports-list --json`.
//
// Before this step, the SPA carried two hand-maintained mirrors of
// the service/port list (`src/dev-server.ts::SERVICE_PORTS_PROD` and
// `src/it/monitoring/MonitoringPage.svelte::SERVICES`). Both drifted
// from `crates/core/boss-ports::lib::PAIRED + SOLO` because no
// build-time link held them in sync; the IT monitoring dashboard
// silently lost `boss-products-api` + `boss-observability` from its
// service list. This step makes the Rust source of truth the only
// place service entries are declared — both the SPA and the dev
// proxy import from `_generated/ports.ts`.
//
// `$REPO_ROOT/target/release/` FIRST, then PATH — the same order
// `infra/lint/no-snapshot-arrays.sh` uses, and deliberately the
// opposite of what a freshness check of an installed binary wants.
//
// The two want different things. Freshness-checking asks "is what's
// INSTALLED current?", so it must resolve the installed binary.
// Codegen asks "what does THIS working tree declare?", so it must
// resolve the binary built from this tree; an entry in PATH came from
// whenever someone last ran a deploy and can be arbitrarily old.
//
// Resolving PATH first is how this file and the lint disagreed
// permanently on any box carrying an installed binary older than the
// tree: codegen regenerated ports.ts from the stale one, the lint
// compared against the fresh one and failed, and the suggested fix
// (`bun run build`) regenerated from the stale one again. On the
// playground that was a 2026-07-01 binary missing `campaigns` and
// `customers` — two services behind, and no amount of rebuilding
// converged.
function findBossPortsList(): string {
  const repoRoot = pathJoin(import.meta.dir, '..', '..', '..');
  const inTarget = pathJoin(repoRoot, 'target', 'release', 'boss-ports-list');
  if (existsSync(inTarget)) return inTarget;
  const onPath = spawnSync('which', ['boss-ports-list'], { encoding: 'utf-8' });
  if (onPath.status === 0 && onPath.stdout.trim()) return onPath.stdout.trim();
  return inTarget;
}
const portsListBin = findBossPortsList();
const generatedPath = pathJoin(import.meta.dir, '_generated', 'ports.ts');
const portsListOut = spawnSync(portsListBin, ['--json'], { encoding: 'utf-8' });
// When the binary is unavailable (e.g. the Bun-only `web` CI job has
// no Rust toolchain), fall back to the committed _generated/ports.ts
// — the file the SPA actually imports. Drift from the Rust source is
// caught separately by infra/lint/no-snapshot-arrays.sh, run where the
// binary exists. Only hard-fail if there's nothing to fall back to.
const canRegenerate = portsListOut.status === 0;
if (!canRegenerate && !existsSync(generatedPath)) {
  throw new Error(
    `boss-ports-list --json failed (status ${portsListOut.status}): ${portsListOut.stderr}\n` +
      `Resolved binary: ${portsListBin}\n` +
      `And no committed _generated/ports.ts to fall back to.\n` +
      `Build the workspace first: cargo build --release --workspace`,
  );
}
type PortRow = { name: string; prod: number; scratch: number | null };
if (canRegenerate) {
const ports: ReadonlyArray<PortRow> = JSON.parse(portsListOut.stdout);
const portsTs = `// AUTO-GENERATED by apps/web/src/build.ts via
// \`boss-ports-list --json\`. Do not edit by hand — the source of
// truth is \`crates/core/boss-ports/src/lib.rs\`. Regenerated on
// every \`bun run build\`; \`infra/lint/no-snapshot-arrays.sh\`
// fails CI if this file drifts from the Rust source.

export type PortRow = Readonly<{ name: string; prod: number; scratch: number | null }>;

export const PORTS: ReadonlyArray<PortRow> = ${JSON.stringify(ports, null, 2)} as const;

/// Convenience lookup by service name. Panics on unknown — every
/// call site is a hardcoded service identifier.
export function portFor(name: string): PortRow {
  const row = PORTS.find((p) => p.name === name);
  if (!row) {
    throw new Error(\`portFor: unknown service '\${name}'\`);
  }
  return row;
}

/// Names of paired services (those with a scratch port).
export const PAIRED_NAMES: ReadonlyArray<string> =
  PORTS.filter((p) => p.scratch !== null).map((p) => p.name);
`;
await mkdir(pathJoin(import.meta.dir, '_generated'), { recursive: true });
await writeFile(
  pathJoin(import.meta.dir, '_generated', 'ports.ts'),
  portsTs,
);
console.log(`codegen: wrote _generated/ports.ts (${ports.length} services)`);
} else {
  console.warn(
    `codegen: boss-ports-list unavailable (${portsListBin}); using the ` +
      `committed _generated/ports.ts. Build the workspace to regenerate it.`,
  );
}

// ---------------------------------------------------------------------------

// Demo mode defaults ON. The public OSS playground wants Demo Mode
// (audit-readonly default + always-visible PersonaSwitcher + amber
// "Demo Mode · read-only" badge) baked into every default build.
const development = process.env['BOSS_DEV'] === '1';

// publicPath controls how the bundler rewrites asset URLs in the
// emitted index.html. Prod uses `/dashboard/` because the gateway
// mounts the SPA under /dashboard; the dev server at port 5174
// serves from root, so BOSS_PUBLIC_PATH=/ lets us run standalone.
const publicPath = process.env['BOSS_PUBLIC_PATH'] ?? '/dashboard/';

const result = await Bun.build({
  entrypoints: ['index.html'],
  outdir: OUT,
  target: 'browser',
  minify: !development,
  sourcemap: 'linked',
  publicPath,
  // Splits dynamic imports (`import('react')`) into their own chunks
  // so the React runtime only loads on pages that mount a plugin-
  // backed step. See src/steps/reactRuntime.ts.
  splitting: true,
  define: {
  },
  plugins: [SveltePlugin({ development })],
});

if (!result.success) {
  for (const log of result.logs) console.error(log);
  process.exit(1);
}

// Post-build entry-fixup. Bun's `entrypoints: ['index.html']` chunking
// has a known glitch where a heavy lazy-loaded dependency can land in
// a non-entry chunk that the rewritten index.html points at, leaving
// the actual `mount(App, …)` call unreferenced and the SPA unmounted.
// The blank-page failure is silent — no JS error, just a never-mounted
// #app. Locate the chunk that contains the main.ts entry shape and
// rewrite the script src ourselves.
{
  const indexPath = pathJoin(OUT, 'index.html');
  const html = await readFile(indexPath, 'utf8');

  const candidates = await readdir(OUT);
  let entryChunk: string | null = null;
  for (const file of candidates) {
    if (!file.endsWith('.js')) continue;
    const body = await readFile(pathJoin(OUT, file), 'utf8');
    // The minifier renames the function symbol but keeps the
    // string literal from `throw new Error('#app element missing
    // from index.html')`. That literal is unique to src/main.ts.
    if (body.includes('#app element missing')) {
      entryChunk = file;
      break;
    }
  }
  if (!entryChunk) {
    console.error('post-build: could not locate the main entry chunk');
    process.exit(1);
  }
  const want = `${publicPath}${entryChunk}`;
  // Newer Bun already points the emitted <script> at the entry chunk, so
  // the rewrite below is a no-op. That's success, not failure — only error
  // if the src is missing or points somewhere other than the entry chunk.
  if (html.includes(`src="${want}"`)) {
    console.log(`post-build: index.html already points at ${want}`);
  } else {
    const fixed = html.replace(
      /<script type="module" crossorigin src="[^"]+"><\/script>/,
      `<script type="module" crossorigin src="${want}"></script>`,
    );
    if (fixed === html) {
      console.error('post-build: failed to rewrite the script src');
      process.exit(1);
    }
    await writeFile(indexPath, fixed);
    console.log(`post-build: rewrote index.html script → ${want}`);
  }
}

console.log(`built ${result.outputs.length} files → ${OUT}/`);
