// AUTO-GENERATED by apps/web/src/build.ts via
// `boss-ports-list --json`. Do not edit by hand — the source of
// truth is `crates/core/boss-ports/src/lib.rs`. Regenerated on
// every `bun run build`; `infra/lint/no-snapshot-arrays.sh`
// fails CI if this file drifts from the Rust source.

export type PortRow = Readonly<{ name: string; prod: number; scratch: number | null }>;

export const PORTS: ReadonlyArray<PortRow> = [
  {
    "name": "shipping",
    "prod": 7100,
    "scratch": 8100
  },
  {
    "name": "messages",
    "prod": 7200,
    "scratch": 8200
  },
  {
    "name": "inventory",
    "prod": 7300,
    "scratch": 8300
  },
  {
    "name": "commerce",
    "prod": 7400,
    "scratch": 8400
  },
  {
    "name": "people",
    "prod": 7500,
    "scratch": 8500
  },
  {
    "name": "assets",
    "prod": 7600,
    "scratch": 8600
  },
  {
    "name": "catalog",
    "prod": 7750,
    "scratch": 8750
  },
  {
    "name": "calendar",
    "prod": 7860,
    "scratch": 8860
  },
  {
    "name": "jobs",
    "prod": 7900,
    "scratch": 8900
  },
  {
    "name": "search",
    "prod": 7960,
    "scratch": null
  },
  {
    "name": "views",
    "prod": 7961,
    "scratch": null
  },
  {
    "name": "simulator",
    "prod": 7010,
    "scratch": null
  },
  {
    "name": "sim-control",
    "prod": 7011,
    "scratch": null
  },
  {
    "name": "clock",
    "prod": 7060,
    "scratch": null
  },
  {
    "name": "ml",
    "prod": 7070,
    "scratch": null
  },
  {
    "name": "ledger",
    "prod": 7080,
    "scratch": null
  },
  {
    "name": "content",
    "prod": 7090,
    "scratch": null
  },
  {
    "name": "policy",
    "prod": 7250,
    "scratch": null
  },
  {
    "name": "classes",
    "prod": 7800,
    "scratch": null
  },
  {
    "name": "locations",
    "prod": 7820,
    "scratch": null
  },
  {
    "name": "subject-kinds",
    "prod": 7830,
    "scratch": null
  },
  {
    "name": "products",
    "prod": 7840,
    "scratch": null
  },
  {
    "name": "campaigns",
    "prod": 7845,
    "scratch": null
  },
  {
    "name": "customers",
    "prod": 7855,
    "scratch": null
  },
  {
    "name": "observability",
    "prod": 7880,
    "scratch": null
  },
  {
    "name": "events",
    "prod": 7150,
    "scratch": null
  },
  {
    "name": "accounts",
    "prod": 7550,
    "scratch": null
  },
  {
    "name": "dispatcher",
    "prod": 7950,
    "scratch": null
  }
] as const;

/// Convenience lookup by service name. Panics on unknown — every
/// call site is a hardcoded service identifier.
export function portFor(name: string): PortRow {
  const row = PORTS.find((p) => p.name === name);
  if (!row) {
    throw new Error(`portFor: unknown service '${name}'`);
  }
  return row;
}

/// Names of paired services (those with a scratch port).
export const PAIRED_NAMES: ReadonlyArray<string> =
  PORTS.filter((p) => p.scratch !== null).map((p) => p.name);
