//! `boss ops <host> <verb> [args…] [--wait]` — file an ops-request from
//! the terminal, validated against the allowlist the runner itself
//! enforces, and optionally wait for the host's answer.
//!
//! THE DOOR HAD NO HANDLE. The ops-request packet (729329c6) replaced
//! ssh: a host's runner polls the system of record for packets naming
//! it, executes one of the allowlisted verbs in infra/ops/verbs/
//! with pattern-checked args, and writes stdout/stderr/exit onto the
//! step — in under two minutes, every time it was tried. But filing one
//! was five hand steps: write `{host, verb, args}` to a scratch file,
//! `boss job file --kind ops-request --subject-id <host> --title … --metadata
//! file.json`, then poll the packet by hand for its `execute` step. Five
//! were filed that way on 2026-09-12 alone (3d6daea9), two the session
//! before. This verb is the handle.
//!
//! ONE ALLOWLIST, READ TWICE, NEVER COPIED. `infra/ops/verbs/<name>.json`
//! — one file per verb, the name being the file name (5086842d) — is
//! the authority the runner enforces on the host; this verb compiles
//! the same files in and applies the same rules at the terminal — unknown
//! verb, a host the verb does not serve, a missing required arg, an arg
//! outside its pattern / one_of / max — so a bad call is refused before
//! a packet exists rather than as a `refused` step a minute later. The
//! runner's check still runs: this is the early copy of its verdict,
//! not a replacement for it. A binary that lags main carries an older
//! allowlist; `boss orient`'s freshness line says so.

use anyhow::{Context, Result, anyhow, bail};
use serde_json::{Value, json};

// `VERB_FILES: &[(&str, &str)]` — (name, file contents) for every
// `infra/ops/verbs/*.json`, generated by build.rs from the directory so
// the list is never authored here (CLAUDE.md §9a).
include!(concat!(env!("OUT_DIR"), "/verb_files.rs"));

/// The allowlist this binary was built with — the same directory the
/// runner assembles on the host (`infra/ops/verbs/`, via
/// `infra/ops/verbs-allowlist.sh`), in the same `{"verbs": {...}}`
/// shape, so `validate` reads what the runner reads.
pub(crate) fn shipped_allowlist() -> Result<Value> {
    let table = VERB_FILES
        .iter()
        .map(|(name, text)| {
            serde_json::from_str::<Value>(text)
                .with_context(|| format!("the compiled-in infra/ops/verbs/{name}.json is not JSON"))
                .map(|spec| ((*name).to_string(), spec))
        })
        .collect::<Result<serde_json::Map<String, Value>>>()?;
    Ok(json!({ "verbs": table }))
}

/// A call the allowlist admits: the args as the packet will carry them
/// (positional strings, defaults filled, omitted optionals dropped) and
/// the title the packet gets.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct Validated {
    pub host: String,
    pub verb: String,
    pub args: Vec<String>,
    pub title: String,
    pub mutating: bool,
    /// The verb declares `requires_approval`: the packet is filed with
    /// `requires_approval: true`, which is what makes ops-request v2's
    /// `approve` step ready, and `args` stops before `plan_sha256` —
    /// the runner appends the SIGNED plan's hash itself (backlog
    /// fd7090cc, design 17835005).
    pub requires_approval: bool,
}

/// Apply the allowlist's rules to a call, exactly as `ops-runner.sh`
/// does (`params[]`: `pattern` | `one_of`, `default`, `optional`, `max`;
/// `hosts`). Pure, over the parsed allowlist, so a test can hand it a
/// fixture.
pub(crate) fn validate(
    verbs: &Value,
    host: &str,
    verb: &str,
    args: &[String],
) -> Result<Validated> {
    let table = verbs
        .get("verbs")
        .and_then(Value::as_object)
        .ok_or_else(|| anyhow!("the allowlist has no `verbs` table"))?;
    let spec = table.get(verb).ok_or_else(|| {
        let mut names: Vec<&str> = table.keys().map(String::as_str).collect();
        names.sort_unstable();
        anyhow!(
            "boss ops: REFUSED — `{verb}` is not an allowlisted verb. The allowlist \
             (infra/ops/verbs/) knows: {}",
            names.join(", ")
        )
    })?;
    let hosts: Vec<&str> = spec
        .get("hosts")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(Value::as_str)
        .collect();
    if !hosts.contains(&host) {
        bail!(
            "boss ops: REFUSED — `{verb}` does not serve host `{host}`; it serves: {}. A runner \
             acts only on an exact host match, so this packet would sit open and unanswered.",
            if hosts.is_empty() {
                "(no host at all)".to_string()
            } else {
                hosts.join(", ")
            }
        );
    }
    let mut params: Vec<&Value> = spec
        .get("params")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .collect();
    // AN APPROVAL VERB IS FILED WITHOUT ITS HASH (backlog fd7090cc).
    // Until this, nothing set `requires_approval` on a filed request, so
    // ops-request v2's `approve` step never became ready, and this verb
    // demanded `plan_sha256` of the filer — a hash only the passkey's
    // signature may choose. The runner renders the plan onto the approve
    // step, and after the signature appends sha256 of the SIGNED plan
    // itself; a filer-supplied one is refused there, so it is refused
    // here first. A verb whose last param is not `plan_sha256`, or that
    // names no `plan_verb`, is one the runner closes refused (its script
    // cannot void a drifted plan, or there is nothing to sign), so that
    // is refused here too — `commission-a-disk` today.
    // Read the way the runner reads it: anything but an absent or
    // literal `false` declaration is REQUIRED, so a typo cannot turn the
    // gate off at either end.
    let requires_approval = !matches!(
        spec.get("requires_approval"),
        None | Some(Value::Null) | Some(Value::Bool(false))
    );
    if requires_approval {
        let last = params
            .last()
            .and_then(|p| p.get("name"))
            .and_then(Value::as_str);
        let plan_verb = spec.get("plan_verb").and_then(Value::as_str);
        if last != Some("plan_sha256") || plan_verb.is_none() {
            bail!(
                "boss ops: REFUSED — `{verb}` declares requires_approval, but {}. The host's \
                 runner refuses an approval verb that cannot re-render its plan and refuse one \
                 that moved since it was signed (design 17835005), so this packet would only \
                 close refused.",
                if plan_verb.is_none() {
                    "names no plan_verb, so there is no plan to sign"
                } else {
                    "its last param is not plan_sha256"
                }
            );
        }
        // WHO MAY APPROVE IS NAMED, BY EMPLOYEE ID (design 03451237 q2,
        // David 2026-09-22: a role is registry data, so a role gate makes
        // the approval depend on whoever can write a policy row). The
        // runner closes refused a verb that names nobody, so filing one is
        // refused here first — judged the way the runner judges it: a
        // non-empty array of non-empty strings.
        let approvers_named = spec
            .get("approvers")
            .and_then(Value::as_array)
            .is_some_and(|a| {
                !a.is_empty() && a.iter().all(|x| x.as_str().is_some_and(|s| !s.is_empty()))
            });
        if !approvers_named {
            bail!(
                "boss ops: REFUSED — `{verb}` declares requires_approval, but names no approvers \
                 (a non-empty list of employee ids in infra/ops/verbs/{verb}.json), so no \
                 passkey could approve it and the host's runner would only close it refused \
                 (design 03451237 q2)."
            );
        }
        params.pop();
    }
    if args.len() > params.len() {
        bail!(
            "boss ops: REFUSED — `{verb}` takes {} arg(s) ({}), got {}: {:?}",
            params.len(),
            params
                .iter()
                .filter_map(|p| p.get("name").and_then(Value::as_str))
                .collect::<Vec<_>>()
                .join(", "),
            args.len(),
            args
        );
    }
    let mut out = Vec::new();
    for (i, p) in params.iter().enumerate() {
        let name = p.get("name").and_then(Value::as_str).unwrap_or("?");
        let given = args.get(i).map(String::as_str);
        let raw = match given {
            Some(v) => v.to_string(),
            None => {
                if let Some(d) = p.get("default").and_then(Value::as_str) {
                    d.to_string()
                } else if p.get("optional").and_then(Value::as_bool).unwrap_or(false) {
                    continue;
                } else {
                    bail!(
                        "boss ops: REFUSED — `{verb}` needs arg `{name}` (position {})",
                        i + 1
                    );
                }
            }
        };
        if let Some(one_of) = p.get("one_of").and_then(Value::as_array) {
            let allowed: Vec<&str> = one_of.iter().filter_map(Value::as_str).collect();
            if !allowed.contains(&raw.as_str()) {
                bail!(
                    "boss ops: REFUSED — arg `{name}` value `{raw}` is not one of {}",
                    allowed.join(", ")
                );
            }
        } else if let Some(pat) = p.get("pattern").and_then(Value::as_str) {
            let re = regex::Regex::new(pat).with_context(|| {
                format!("the allowlist's pattern for {verb}.{name} is not a regex")
            })?;
            if !re.is_match(&raw) {
                bail!("boss ops: REFUSED — arg `{name}` value `{raw}` does not match {pat}");
            }
        }
        if let Some(max) = p.get("max").and_then(Value::as_i64)
            && raw.parse::<i64>().map(|n| n > max).unwrap_or(false)
        {
            bail!("boss ops: REFUSED — arg `{name}` value `{raw}` exceeds max {max}");
        }
        out.push(raw);
    }
    let mutating = spec
        .get("about")
        .and_then(Value::as_str)
        .is_some_and(|a| a.contains("MUTATING"));
    let title = if out.is_empty() {
        format!("{verb} on {host}")
    } else {
        format!("{verb} {} on {host}", out.join(" "))
    };
    Ok(Validated {
        host: host.to_string(),
        verb: verb.to_string(),
        args: out,
        title,
        mutating,
        requires_approval,
    })
}

/// The packet's job metadata: the request as the runner reads it, and
/// `requires_approval` when the verb declares it — the flag that makes
/// the `approve` step ready. It is a routing fact, never an approval:
/// the runner reads the requirement off the verb and the approval off
/// the step's sign-off record.
pub(crate) fn request_metadata(v: &Validated) -> Value {
    let mut md = json!({"host": v.host, "verb": v.verb, "args": v.args});
    if v.requires_approval {
        md["requires_approval"] = json!(true);
    }
    md
}

/// The answer a closed ops-request carries on its `execute` step.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct Answer {
    pub disposition: String,
    pub exit_code: Option<String>,
    pub output: String,
    pub runner_host: String,
}

/// Read the `execute` step's record off a packet, or `None` while the
/// host has not answered.
pub(crate) fn answer_of(job: &Value) -> Option<Answer> {
    let step_of = |slug: &str| {
        job.get("steps")
            .and_then(Value::as_array)
            .into_iter()
            .flatten()
            .find(|s| s.get("spec_slug").and_then(Value::as_str) == Some(slug))
    };
    // A request the runner closed through its `refused` terminal while
    // `execute` still waited behind the approve step — a verb that
    // cannot carry an approval, or a plan verb that refused — answers
    // there, with the reason on that step.
    let closed_refused = || {
        let s = step_of("refused")?;
        if s.get("status").and_then(Value::as_str) != Some("completed") {
            return None;
        }
        let md = s.get("metadata")?;
        Some(Answer {
            disposition: "refused".to_string(),
            exit_code: None,
            output: md.get("reason").and_then(Value::as_str)?.to_string(),
            runner_host: md
                .get("runner_host")
                .and_then(Value::as_str)
                .unwrap_or_default()
                .to_string(),
        })
    };
    let Some(md) = step_of("execute").and_then(|s| s.get("metadata")) else {
        return closed_refused();
    };
    let Some(disposition) = md.get("disposition").and_then(Value::as_str) else {
        return closed_refused();
    };
    let disposition = disposition.to_string();
    Some(Answer {
        disposition,
        exit_code: md
            .get("exit_code")
            .and_then(Value::as_str)
            .map(str::to_string),
        output: md
            .get("output")
            .and_then(Value::as_str)
            .unwrap_or_default()
            .to_string(),
        runner_host: md
            .get("runner_host")
            .and_then(Value::as_str)
            .unwrap_or_default()
            .to_string(),
    })
}

/// The one-line verdict `--wait` ends with, and whether it is a success.
pub(crate) fn verdict_line(id8: &str, v: &Validated, a: &Answer) -> (String, bool) {
    match (a.disposition.as_str(), a.exit_code.as_deref()) {
        ("answered", Some("0")) => (
            format!(
                "boss ops: answered — {} on {} (packet {id8}, exit 0)",
                v.verb, a.runner_host
            ),
            true,
        ),
        ("answered", code) => (
            format!(
                "boss ops: answered — {} on {} (packet {id8}, exit {})",
                v.verb,
                a.runner_host,
                code.unwrap_or("?")
            ),
            false,
        ),
        (d, _) => (
            format!("boss ops: {d} — {} on {} (packet {id8})", v.verb, v.host),
            false,
        ),
    }
}

pub async fn run(
    host: String,
    verb: String,
    args: Vec<String>,
    wait: bool,
    dry_run: bool,
) -> Result<()> {
    let verbs = shipped_allowlist()?;
    let v = validate(&verbs, &host, &verb, &args)?;
    if v.mutating {
        eprintln!(
            "boss ops: `{}` is MUTATING on {} — the host's runner applies the verb's own bounds; \
             this files the request, it does not widen them.",
            v.verb, v.host
        );
    }
    if v.requires_approval {
        eprintln!(
            "boss ops: `{}` requires a passkey approval — the runner on {} renders its plan onto \
             the packet's approve step, and runs it only after that step is signed with a \
             passkey (within ten minutes of the signature, once).",
            v.verb, v.host
        );
    }
    let metadata = request_metadata(&v);
    if dry_run {
        println!(
            "boss ops: DRY RUN — would file ops-request \"{}\" (metadata {metadata})",
            v.title
        );
        return Ok(());
    }
    let http = reqwest::Client::new();
    let owner = crate::identity::sign(&reqwest::Method::POST, "/api/jobs")?;
    let body = crate::job::envelope(
        "ops-request",
        &v.title,
        None,
        Some(&v.host),
        &owner,
        Some(metadata),
    );
    let created = crate::gate::api(&http, reqwest::Method::POST, "/api/jobs", Some(body))
        .await?
        .context("the create returned no body")?;
    let id = created
        .get("id")
        .and_then(Value::as_str)
        .context("the create returned no id — refusing to call that filed")?
        .to_string();
    let id8 = &id[..8.min(id.len())];
    println!("boss ops: filed {id8} — \"{}\"", v.title);
    if !wait {
        println!(
            "boss ops: the runner on {} polls about once a minute; `boss job get {id8}` reads the answer",
            v.host
        );
        return Ok(());
    }
    // The packet is the record; poll it, as `boss gate --wait` does.
    // A host whose runner is down never answers: say so after a bound
    // rather than waiting forever on a packet nobody will touch.
    let deadline = std::time::Instant::now() + std::time::Duration::from_secs(15 * 60);
    loop {
        tokio::time::sleep(std::time::Duration::from_secs(10)).await;
        let job = crate::gate::api(
            &http,
            reqwest::Method::GET,
            &format!("/api/jobs/{id}"),
            None,
        )
        .await?
        .context("the filed packet vanished")?;
        let job = job.get("data").unwrap_or(&job).clone();
        if let Some(a) = answer_of(&job) {
            let (line, ok) = verdict_line(id8, &v, &a);
            if !a.output.trim().is_empty() {
                println!("{}", a.output.trim_end());
            }
            println!("{line}");
            if ok {
                return Ok(());
            }
            bail!("{line}");
        }
        if std::time::Instant::now() > deadline {
            bail!(
                "boss ops: no answer from {} in 15 minutes — its runner polls every minute, so it \
                 is down or cannot reach the system of record. The packet {id8} stays open and \
                 visibly unanswered; `boss job get {id8}` when the host is back.",
                v.host
            );
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture() -> Value {
        json!({"verbs": {
            "journal-tail": {"about": "last N journal lines", "hosts": ["boss-gcp", "forge"],
                "argv": ["journalctl", "-u", "{1}", "-n", "{2}", "--no-pager"],
                "params": [
                    {"name": "unit", "pattern": "^[A-Za-z0-9@._][A-Za-z0-9@._-]*$"},
                    {"name": "lines", "pattern": "^[0-9]{1,3}$", "default": "100", "max": 200}]},
            "delete-orphan-object": {"about": "MUTATING — delete one undeclared object", "hosts": ["forge"],
                "argv": ["infra/forge/delete-orphan-object.sh", "{1}", "{2}"],
                "params": [
                    {"name": "object", "pattern": "^[A-Z][A-Za-z0-9]{0,62}/[a-z0-9-]+/[a-z0-9.-]+$"},
                    {"name": "mode", "one_of": ["--dry-run"], "optional": true}]},
            "uptime": {"about": "uptime", "hosts": ["boss-gcp", "forge"], "argv": ["uptime"], "params": []}
        }})
    }

    /// The same rules the runner applies on the host, applied here
    /// first: each refusal names what the allowlist would have said.
    #[test]
    fn the_terminal_refuses_what_the_runner_would_refuse() {
        let v = fixture();
        let e = validate(&v, "forge", "rm-rf", &[]).unwrap_err().to_string();
        assert!(
            e.contains("not an allowlisted verb") && e.contains("journal-tail"),
            "{e}"
        );
        let e = validate(&v, "w-1", "uptime", &[]).unwrap_err().to_string();
        assert!(
            e.contains("does not serve host `w-1`") && e.contains("boss-gcp, forge"),
            "{e}"
        );
        let e = validate(&v, "forge", "journal-tail", &[])
            .unwrap_err()
            .to_string();
        assert!(e.contains("needs arg `unit`"), "{e}");
        let e = validate(
            &v,
            "forge",
            "journal-tail",
            &["boss-x.service".into(), "5000".into()],
        )
        .unwrap_err()
        .to_string();
        assert!(e.contains("does not match"), "{e}");
        let e = validate(
            &v,
            "forge",
            "journal-tail",
            &["boss-x.service".into(), "201".into()],
        )
        .unwrap_err()
        .to_string();
        assert!(e.contains("exceeds max 200"), "{e}");
        let e = validate(
            &v,
            "forge",
            "delete-orphan-object",
            &["CronJob/boss-dev/x".into(), "--force".into()],
        )
        .unwrap_err()
        .to_string();
        assert!(e.contains("not one of --dry-run"), "{e}");
        let e = validate(&v, "forge", "uptime", &["extra".into()])
            .unwrap_err()
            .to_string();
        assert!(e.contains("takes 0 arg(s)"), "{e}");
    }

    /// What the allowlist admits is carried exactly as the runner will
    /// read it: defaults filled, omitted optionals dropped, a title a
    /// reader can scan, and MUTATING said out loud.
    #[test]
    fn an_admitted_call_carries_the_args_as_the_runner_reads_them() {
        let v = fixture();
        let ok = validate(
            &v,
            "boss-gcp",
            "journal-tail",
            &["boss-codebase-metrics.service".into()],
        )
        .unwrap();
        assert_eq!(
            ok.args,
            vec!["boss-codebase-metrics.service", "100"],
            "the default is filled"
        );
        assert_eq!(
            ok.title,
            "journal-tail boss-codebase-metrics.service 100 on boss-gcp"
        );
        assert!(!ok.mutating);
        let ok = validate(
            &v,
            "forge",
            "delete-orphan-object",
            &["CronJob/boss-dev/gate-seed-prepare".into()],
        )
        .unwrap();
        assert_eq!(
            ok.args,
            vec!["CronJob/boss-dev/gate-seed-prepare"],
            "the optional mode is dropped, not defaulted"
        );
        assert!(ok.mutating);
        let ok = validate(&v, "forge", "uptime", &[]).unwrap();
        assert_eq!(ok.title, "uptime on forge");
    }

    /// The compiled-in set IS the directory: the names build.rs generated
    /// equal the `*.json` files under `infra/ops/verbs/` as they stand
    /// now, and each is named by its file. This is the one place the
    /// Rust derivation of "name = file name" is measured against the
    /// shell one (`verbs-allowlist.sh`), because `include_str!` needs
    /// literal paths and so this reader cannot call that script.
    ///
    /// It also catches the shared-target-dir staleness boss-testing's
    /// build.rs documents: a `VERB_FILES` linked from a neighbouring
    /// checkout's build would disagree with this checkout's directory.
    #[test]
    fn the_compiled_in_verbs_are_the_directory() {
        let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../infra/ops/verbs");
        let mut on_disk: Vec<String> = std::fs::read_dir(&dir)
            .expect("infra/ops/verbs/ exists")
            .map(|e| e.unwrap().path())
            .filter(|p| p.extension().is_some_and(|x| x == "json"))
            .map(|p| p.file_stem().unwrap().to_string_lossy().into_owned())
            .collect();
        on_disk.sort();
        let mut compiled: Vec<String> = VERB_FILES.iter().map(|(n, _)| (*n).to_string()).collect();
        compiled.sort();
        assert_eq!(
            compiled, on_disk,
            "VERB_FILES is not infra/ops/verbs/*.json — rebuild"
        );
        assert!(
            !dir.join("../verbs.json").exists(),
            "infra/ops/verbs.json is back — the directory is the allowlist (5086842d)"
        );
        for (name, text) in VERB_FILES {
            let spec: Value =
                serde_json::from_str(text).unwrap_or_else(|e| panic!("{name}.json: {e}"));
            assert!(
                spec.is_object() && spec.get("verbs").is_none(),
                "{name}.json must describe ONE verb"
            );
            assert_eq!(
                std::fs::read_to_string(dir.join(format!("{name}.json"))).unwrap(),
                *text,
                "{name}.json on disk differs from the compiled copy"
            );
        }
    }

    /// The shipped allowlist parses and every verb validates its own
    /// happy path — so a verb-file edit that breaks the terminal half is
    /// caught here, not at the first `boss ops`.
    #[test]
    fn the_shipped_allowlist_is_one_this_verb_can_read() {
        let v = shipped_allowlist().expect("the verb files parse");
        let table = v["verbs"].as_object().expect("a verbs table");
        assert!(table.len() >= 16, "{} verbs", table.len());
        for (name, spec) in table {
            let host = spec["hosts"][0].as_str().expect("a host");
            // No args: a verb whose every param has a default or is optional validates;
            // one with a required param refuses naming it — either way it is readable.
            // commission-a-disk is the one approval verb the runner cannot carry (its
            // script takes no plan_sha256), and is refused for that before any arg.
            match validate(&v, host, name, &[]) {
                Ok(ok) => assert!(ok.title.ends_with(&format!("on {host}"))),
                Err(e) if name == "commission-a-disk" => {
                    assert!(e.to_string().contains("plan_sha256"), "{name}: {e}")
                }
                Err(e) => assert!(e.to_string().contains("needs arg"), "{name}: {e}"),
            }
        }
    }

    /// AN APPROVAL VERB IS FILED WITH THE FLAG AND WITHOUT THE HASH
    /// (backlog fd7090cc). Measured on origin/main 87c2e366: nothing set
    /// `requires_approval` on a filed ops-request, so the approve step
    /// was never reached, and this verb asked the filer for `plan_sha256`
    /// — the one value only a passkey signature may choose. Now the
    /// packet carries the flag, the args stop before the hash, and a
    /// filer who supplies one is refused, as the runner would.
    #[test]
    fn an_approval_verb_files_the_flag_and_never_the_hash() {
        let v = shipped_allowlist().expect("the verb files parse");
        let ok = validate(&v, "forge", "reap-terminated-pods", &[]).unwrap();
        assert!(ok.requires_approval);
        assert!(ok.args.is_empty(), "{:?}", ok.args);
        assert_eq!(
            request_metadata(&ok),
            json!({"host": "forge", "verb": "reap-terminated-pods", "args": [],
                   "requires_approval": true})
        );
        let ok = validate(
            &v,
            "forge",
            "merge-tenant-main",
            &["playground".into(), "tenant/merge-1".into()],
        )
        .unwrap();
        assert_eq!(ok.args, vec!["playground", "tenant/merge-1"]);
        assert_eq!(request_metadata(&ok)["requires_approval"], true);

        let hash = "0".repeat(64);
        let e = validate(
            &v,
            "forge",
            "reap-terminated-pods",
            std::slice::from_ref(&hash),
        )
        .unwrap_err()
        .to_string();
        assert!(e.contains("takes 0 arg(s)"), "{e}");
        let e = validate(
            &v,
            "forge",
            "merge-tenant-main",
            &["playground".into(), "tenant/merge-1".into(), hash],
        )
        .unwrap_err()
        .to_string();
        assert!(e.contains("takes 2 arg(s)"), "{e}");

        // A read carries no flag at all — an absent value reads false in
        // the approve step's predicate, so every read runs as it did.
        let ok = validate(&v, "forge", "uptime", &[]).unwrap();
        assert!(!ok.requires_approval);
        assert!(request_metadata(&ok).get("requires_approval").is_none());

        // The disk verb stays inert: the runner would close it refused.
        let e = validate(
            &v,
            "forge",
            "commission-a-disk",
            &["/dev/disk/by-id/nvme-X-0000".into(), "/srv/data".into()],
        )
        .unwrap_err()
        .to_string();
        assert!(
            e.contains("requires_approval") && e.contains("plan_sha256"),
            "{e}"
        );
    }

    /// AN APPROVAL VERB NAMES WHO MAY APPROVE IT (design 03451237 q2:
    /// named employee ids, not a role). The runner closes refused a verb
    /// that names nobody, so filing one is refused here first, the way a
    /// verb with no plan verb is — and the shipped verbs name David.
    #[test]
    fn an_approval_verb_that_names_no_approver_is_refused_at_filing() {
        let mut v = shipped_allowlist().expect("the verb files parse");
        assert_eq!(
            v["verbs"]["reap-terminated-pods"]["approvers"],
            json!(["emp-david"])
        );
        for bad in [
            Value::Null,
            json!([]),
            json!("emp-david"),
            json!([""]),
            json!([7]),
        ] {
            let spec = v["verbs"]["reap-terminated-pods"].as_object_mut().unwrap();
            if bad.is_null() {
                spec.remove("approvers");
            } else {
                spec.insert("approvers".into(), bad.clone());
            }
            let e = validate(&v, "forge", "reap-terminated-pods", &[])
                .unwrap_err()
                .to_string();
            assert!(e.contains("approvers"), "{bad}: {e}");
        }
    }

    /// A request the runner closed through its `refused` terminal —
    /// execute still pending behind the approve step — answers there,
    /// so `--wait` ends on the reason instead of timing out.
    #[test]
    fn a_request_closed_refused_before_execute_answers_with_its_reason() {
        let v = validate(&fixture(), "forge", "uptime", &[]).unwrap();
        let job = json!({"steps": [
            {"spec_slug": "execute", "status": "skipped", "metadata": {"authority_role": "platform-admin"}},
            {"spec_slug": "refused", "status": "completed",
             "metadata": {"outcome_kind": "aborted", "runner_host": "forge",
                          "reason": "the plan verb plan-a-pod-reap refused (exit 78)"}}
        ]});
        let a = answer_of(&job).expect("the refused terminal is an answer");
        assert_eq!(a.disposition, "refused");
        assert!(a.output.contains("plan-a-pod-reap refused"), "{a:?}");
        let (line, ok) = verdict_line("abcd1234", &v, &a);
        assert!(!ok && line.starts_with("boss ops: refused"), "{line}");
        // A refused step not yet completed is no answer.
        let open = json!({"steps": [
            {"spec_slug": "execute", "status": "pending", "metadata": {}},
            {"spec_slug": "refused", "status": "pending", "metadata": {"outcome_kind": "aborted"}}
        ]});
        assert!(answer_of(&open).is_none());
    }

    /// `unit-list` takes one glob of unit-name characters and nothing a
    /// shell could read: `boss-*` is admitted, a space or a `;` is not,
    /// and the runner receives it as its own argv element.
    #[test]
    fn unit_list_admits_a_glob_and_refuses_a_shell() {
        let v = shipped_allowlist().expect("the verb files parse");
        let ok = validate(&v, "boss-gcp", "unit-list", &["boss-*".into()]).unwrap();
        assert_eq!(ok.args, vec!["boss-*".to_string()]);
        assert!(!ok.mutating);
        for bad in ["boss-* ; id", "boss-*;id", "$(id)", "a b"] {
            let e = validate(&v, "boss-gcp", "unit-list", &[bad.into()])
                .unwrap_err()
                .to_string();
            assert!(e.contains("does not match"), "{bad}: {e}");
        }
    }

    /// The answer is read off the packet's execute step and judged the
    /// way the runner wrote it: answered+0 is success; anything else is
    /// a non-zero exit for the caller.
    #[test]
    fn the_answer_is_judged_off_the_execute_step() {
        let v = validate(&fixture(), "forge", "uptime", &[]).unwrap();
        let job = json!({"steps": [
            {"spec_slug": "filed", "status": "completed", "metadata": {}},
            {"spec_slug": "execute", "status": "completed",
             "metadata": {"disposition": "answered", "exit_code": "0", "output": " 18:40:01 up 9 days\n", "runner_host": "forge"}}
        ]});
        let a = answer_of(&job).unwrap();
        let (line, ok) = verdict_line("abcd1234", &v, &a);
        assert!(
            ok && line.contains("exit 0") && line.contains("on forge"),
            "{line}"
        );
        let refused = json!({"steps": [{"spec_slug": "execute", "status": "completed",
            "metadata": {"disposition": "refused", "output": "verb x does not serve this host", "runner_host": "forge"}}]});
        let (line, ok) = verdict_line("abcd1234", &v, &answer_of(&refused).unwrap());
        assert!(!ok && line.starts_with("boss ops: refused"), "{line}");
        assert!(
            answer_of(
                &json!({"steps": [{"spec_slug": "execute", "status": "ready", "metadata": {}}]})
            )
            .is_none()
        );
    }
}
