//! Derives the estate spool's defaults from the shell observer's own
//! library, so the two halves of one retain-and-replay mechanism cannot
//! disagree about where readings wait or how many of them may.
//!
//! CLAUDE.md §9a, and the same collapse `boss-testing/build.rs` makes:
//! the spool directory and its cap were already defined, once, in
//! `infra/estate/observe-lib.sh` — the host observer's half of this
//! mechanism (packet ec50db46). Restating them in Rust would be a fact
//! living twice under a sync comment, which is the shape that has
//! already cost this repo four re-rails and two silently-missing
//! tables. So the shell file stays the single definition and this
//! script reads it; the Rust side cannot drift because it derives.
//!
//! It parses exactly the POSIX default idiom the library uses:
//!
//! ```sh
//! SPOOL_DIR="${SPOOL_DIR:-/var/tmp/boss-estate-spool}"
//! SPOOL_MAX="${SPOOL_MAX:-200}"
//! ```
//!
//! A rename, a removal, or a reformat that breaks the idiom fails the
//! BUILD, naming the file and the variable — the loud failure a sync
//! comment would not have given.

use std::path::PathBuf;

/// Pull `NAME="${NAME:-VALUE}"` out of a POSIX shell file.
fn shell_default(src: &str, name: &str) -> Option<String> {
    let open = format!("{name}=\"${{{name}:-");
    src.lines()
        .map(str::trim)
        .find_map(|l| l.strip_prefix(&open))
        .and_then(|rest| rest.strip_suffix("}\""))
        .map(str::to_string)
}

fn main() {
    let crate_dir = PathBuf::from(
        std::env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by cargo"),
    );
    // crates/orchestrators/boss-dispatcher-handlers -> repo root
    let lib = crate_dir
        .join("../../../infra/estate/observe-lib.sh")
        .canonicalize()
        .expect("infra/estate/observe-lib.sh must exist relative to the crate root");
    println!("cargo:rerun-if-changed={}", lib.display());
    println!("cargo:rerun-if-changed=build.rs");

    let src =
        std::fs::read_to_string(&lib).unwrap_or_else(|e| panic!("reading {}: {e}", lib.display()));

    let dir = shell_default(&src, "SPOOL_DIR").unwrap_or_else(|| {
        panic!(
            "{} no longer defines SPOOL_DIR as SPOOL_DIR=\"${{SPOOL_DIR:-...}}\" — \
             the estate spool's directory is defined there and derived here; \
             restore the idiom or move the definition deliberately",
            lib.display()
        )
    });
    let max = shell_default(&src, "SPOOL_MAX").unwrap_or_else(|| {
        panic!(
            "{} no longer defines SPOOL_MAX as SPOOL_MAX=\"${{SPOOL_MAX:-...}}\" — \
             the estate spool's cap is defined there and derived here",
            lib.display()
        )
    });
    let max: usize = max.parse().unwrap_or_else(|e| {
        panic!(
            "{} defines SPOOL_MAX as {max:?}, which is not a count: {e}",
            lib.display()
        )
    });
    assert!(
        max > 0,
        "{} defines a spool cap of 0 — that retains nothing",
        lib.display()
    );
    assert!(
        dir.starts_with('/'),
        "{} defines SPOOL_DIR as {dir:?}; a relative spool would follow the \
         working directory of whatever ran the observer",
        lib.display()
    );

    let out = format!(
        "// @generated by build.rs from infra/estate/observe-lib.sh — do not edit.\n\
         /// Where retained estate readings wait. Defined once, in the shell\n\
         /// observer's library, and derived here (build.rs).\n\
         pub const SPOOL_DIR_DEFAULT: &str = {dir:?};\n\
         /// How many may wait before the OLDEST is dropped. Same definition.\n\
         pub const SPOOL_MAX_DEFAULT: usize = {max};\n"
    );
    let dest = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR is set by cargo"))
        .join("estate_spool_defaults.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("writing {}: {e}", dest.display()));
}
